repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # specify the version you want
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
