# This workflow will install Python dependencies, run tests, and lint with Python 3.10

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"  # Adjust this version if necessary

      # Step 3: Upgrade pip and Install Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest  # Install flake8 for linting and pytest for testing
          # Install torch from the official PyTorch repository with extra-index-url
          pip install torch==2.4.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu
          # Install other dependencies from requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run linting with flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 5: Run tests with pytest
      - name: Test with pytest
        run: |
          pytest tests/  # Adjust this path if your tests are in a specific folder
